import type { NewsEvent } from './api';

export const MOCK_NEWS: NewsEvent[] = [
    {
        id: 101,
        documentId: 'mock-1',
        title: 'NFA Launches New Fortification Guidelines for 2024',
        slug: 'nfa-launches-new-guidelines-2024',
        excerpt: 'The National Fortification Alliance today released the updated regulatory standards for edible oil and wheat flour, aiming to reach 90% compliance by the end of the year.',
        body: '<p>The National Fortification Alliance (NFA) is proud to announce the release of the updated regulatory standards for the mandatory fortification of edible oil and wheat flour in Nigeria.</p><h2>A Milestone in Nutrition</h2><p>This comprehensive update aligns our national standards with the latest global health guidelines set by the World Health Organization (WHO), ensuring that staple foods provide the optimal levels of essential vitamins and minerals.</p><ul><li>Increased Vitamin A requirements for vegetable oil.</li><li>Enhanced iron and folic acid ranges for wheat flour.</li><li>Stricter QA/QC protocols for inline testing.</li></ul><p>We invite all certified processors to download the new technical handbook from our Guidelines section.</p>',
        category: 'news',
        date: '2024-03-15',
        is_featured: true,
        publishedAt: '2024-03-15T10:00:00Z',
        image: { id: 0, documentId: '', url: '' },
        gallery: [
            { id: 1001, documentId: 'g1', url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800', alternativeText: 'Guidelines launch event' },
            { id: 1002, documentId: 'g2', url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800', alternativeText: 'Stakeholders reviewing documents' },
            { id: 1003, documentId: 'g3', url: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800', alternativeText: 'Laboratory testing' },
        ],
    },
    {
        id: 102,
        documentId: 'mock-2',
        title: 'Annual Fortification Audit Reveals 20% Increase in Compliance',
        slug: 'annual-fortification-audit-reveals-increase',
        excerpt: 'NAFDAC\'s latest nationwide audit shows a significant improvement in industry compliance across all six mandated food vehicles.',
        body: '<p>The National Agency for Food and Drug Administration and Control (NAFDAC) has published the results of the 2023 Nationwide Fortification Audit, revealing a remarkable 20% year-over-year increase in industry compliance.</p><h2>Key Findings</h2><p>The audit covered over 200 certified food processing facilities across all 36 states, analyzing thousands of end-product samples for micronutrient adequacy.</p><p>Wheat flour and vegetable oil sectors showed the highest levels of adherence, driven largely by recent capacity building initiatives supported by the WFP and GAIN.</p>',
        category: 'report',
        date: '2024-02-28',
        is_featured: true,
        publishedAt: '2024-02-28T10:00:00Z',
        image: { id: 0, documentId: '', url: '' },
        gallery: [
            { id: 1004, documentId: 'g4', url: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800', alternativeText: 'Audit team in facility' },
            { id: 1005, documentId: 'g5', url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', alternativeText: 'Data analysis' },
        ],
    },
    {
        id: 103,
        documentId: 'mock-3',
        title: 'Stakeholder Workshop on Digital Monitoring Tools',
        slug: 'stakeholder-workshop-digital-monitoring',
        excerpt: 'Join us for a hands-on technical workshop introducing the DFQT+ digital monitoring platform for real-time tracking of fortification levels.',
        body: '<p>The NFA, in collaboration with our technical partners, is hosting a two-day workshop on the implementation of the new DFQT+ digital monitoring platform.</p><h2>About the Event</h2><p>This event is designed for quality assurance managers, regulatory inspectors, and IT personnel involved in the fortification supply chain.</p><p><strong>Date:</strong> April 10-11, 2024<br/><strong>Location:</strong> NFA Secretariat, UN House, Abuja<br/><strong>Format:</strong> In-person and Virtual</p><p>Registration is mandatory for all participating food processing companies.</p>',
        category: 'event',
        date: '2024-04-10',
        is_featured: true,
        publishedAt: '2024-04-01T10:00:00Z',
        image: { id: 0, documentId: '', url: '' },
        gallery: [
            { id: 1006, documentId: 'g6', url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800', alternativeText: 'Workshop presentation' },
            { id: 1007, documentId: 'g7', url: 'https://images.unsplash.com/photo-1560439513-74b037a25d84?w=800', alternativeText: 'Participants during breakout session' },
            { id: 1008, documentId: 'g8', url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800', alternativeText: 'Digital platform demonstration' },
            { id: 1009, documentId: 'g9', url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800', alternativeText: 'Group discussion' },
        ],
    },
    {
        id: 104,
        documentId: 'mock-4',
        title: 'WFP and NFA Partner to Expand Rice Fortification Across Nigeria',
        slug: 'wfp-nfa-expand-rice-fortification',
        excerpt: 'New partnership aims to scale up rice fortification to reach 50 million Nigerians by 2025.',
        body: '<p>The World Food Programme and the National Fortification Alliance have announced a groundbreaking partnership to expand rice fortification across Nigeria.</p><h2>Partnership Goals</h2><p>This initiative will provide technical support, capacity building, and funding to rice millers across the country to adopt fortification practices.</p>',
        category: 'news',
        date: '2024-03-20',
        is_featured: true,
        publishedAt: '2024-03-20T10:00:00Z',
        image: { id: 0, documentId: '', url: '' },
    },
    {
        id: 105,
        documentId: 'mock-5',
        title: 'Success Story: How Fortification is Reducing Anemia in Nigerian Children',
        slug: 'fortification-reducing-anemia-children',
        excerpt: 'Recent health surveys show a 35% reduction in childhood anemia in areas with high fortification compliance.',
        body: '<p>A new health impact study reveals the remarkable success of Nigeria\'s food fortification program in combating childhood anemia.</p><h2>Key Results</h2><p>Children in regions with over 80% fortification compliance showed significantly better nutrition indicators compared to baseline measurements from 2020.</p>',
        category: 'report',
        date: '2024-03-10',
        is_featured: true,
        publishedAt: '2024-03-10T10:00:00Z',
        image: { id: 0, documentId: '', url: '' },
    },
    {
        id: 106,
        documentId: 'mock-6',
        title: 'NAFDAC Approves 25 New Fortification Facilities',
        slug: 'nafdac-approves-new-facilities',
        excerpt: 'Regulatory milestone as 25 additional food processing facilities receive certification for fortified production.',
        body: '<p>NAFDAC has announced the certification of 25 new food processing facilities, marking a significant expansion in Nigeria\'s fortification capacity.</p><p>These new facilities span across 12 states and will increase national fortified food production by an estimated 30%.</p>',
        category: 'news',
        date: '2024-03-05',
        is_featured: true,
        publishedAt: '2024-03-05T10:00:00Z',
        image: { id: 0, documentId: '', url: '' },
    }
];
